# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gremlins < Formula
  desc "A mutation testing tool for Go."
  homepage "https://github.com/go-gremlins/gremlins"
  version "0.2.0"
  license "Apache 2.0 License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-gremlins/gremlins/releases/download/v0.2.0/gremlins_0.2.0_darwin_amd64.tar.gz"
      sha256 "0fccba87a9eec5bc8e51b9079ec4a964feafe1c96fbf551401e1996c8cdeaf49"

      def install
        bin.install "gremlins"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-gremlins/gremlins/releases/download/v0.2.0/gremlins_0.2.0_darwin_arm64.tar.gz"
      sha256 "72d450b4dc4d114cca33533ea312d57e7b0fe0c5e348280d2574c5d0f2b2f98f"

      def install
        bin.install "gremlins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/go-gremlins/gremlins/releases/download/v0.2.0/gremlins_0.2.0_linux_amd64.tar.gz"
      sha256 "d1fce8484ebd2023314f82b43d6e5fc52e2018a2ff9f5092259748bddd0697d3"

      def install
        bin.install "gremlins"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-gremlins/gremlins/releases/download/v0.2.0/gremlins_0.2.0_linux_arm64.tar.gz"
      sha256 "b0779d3a142a7191c9581644835717705af23c370bf80ed1edf2ddef5a064fd9"

      def install
        bin.install "gremlins"
      end
    end
  end

  test do
    system "#{bin}/gremlins --version"
  end
end
