# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gremlins < Formula
  desc "A mutation testing tool for Go."
  homepage "https://gremlins.dev"
  version "0.3.0"
  license "Apache-2.0 License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/go-gremlins/gremlins/releases/download/v0.3.0/gremlins_0.3.0_darwin_arm64.tar.gz"
      sha256 "66f27492f924e8c24c737a5ea54d217d270aafa0a6607036378f2a6415723b10"

      def install
        bin.install "gremlins"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-gremlins/gremlins/releases/download/v0.3.0/gremlins_0.3.0_darwin_amd64.tar.gz"
      sha256 "ceca052fb797b1de9affe6389a6619f8cd42aeb68a61a3083fc8db2722f0fb4b"

      def install
        bin.install "gremlins"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/go-gremlins/gremlins/releases/download/v0.3.0/gremlins_0.3.0_linux_amd64.tar.gz"
      sha256 "4bf259e1748082d1b9eaac33d6856a9276a874224dd12f82fec714a7a8bfe7db"

      def install
        bin.install "gremlins"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-gremlins/gremlins/releases/download/v0.3.0/gremlins_0.3.0_linux_arm64.tar.gz"
      sha256 "ee4539de31ca8e33c01512cf705aa3a4ca31d16f242a827e7ed6e04b03244b3b"

      def install
        bin.install "gremlins"
      end
    end
  end

  test do
    system "#{bin}/gremlins --version"
  end
end
